apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zjuyw2aj8-go 
  janus-idp.io/tekton: zjuyw2aj8-go
  backstage.io/kubernetes-id: zjuyw2aj8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zjuyw2aj8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  